language: node_js
node_js: lts/carbon
services: 
  - docker
addons:
  apt:
    packages:
    - libsecret-1-0
script:
  - chmod +x ./scripts/docker-deploy.sh
deploy:
  - provider: npm
    api_key:
      secure: Ti3IyRPLeMWF3LBy20hz6RVYra+wpYFubrcGuJaNZwY3C7nUnFCFSGpHryUoiaX4Ar56WcbIpqqMc9KpQUF81PM8sb7HKvh+Rpe+IGNBlsolQ0UDO4LNsN/qs8y6KMMOKuchqLA32+DQaX0ajHfBel03f7I7w0B3//J4YM19BQKmi5EmVHxqtXndH2rPja29XwVVK/MMTgaib43Tb58IUu8fD/wN8991Hb4vW8hUOagJOV7XHFUI3V56fRyOGxpPwZmf5B0aHbaAeUERbE0G9yXL14LregKJji47I/9Rvz1bZIzO08jMO9h0sxHjpUqfLqgNcdUZCoEJliUX6yeupu+yITf3cMdxx5VBNySqGIScJ4n/zvzsx7Q+uAfyaknKnf73PyuHAyC7tPa9f6ZZNMKDAQfy/LGOi5vJtwl87QLMF/TNt5XA9QI/aQuUariPvO1evSizTRzQ91E8n4NitT/TMiw5C815yv7y2HttFCCt3nArYqoxPmVO1L7LilD3dSdFXaIPVwkWXIviGqb5TkfF5F8yY2aMEqHeFW3f2n+JR6iZhoXwexiyViRXUsCPox/31HowU64EI8AxNtbBxz+k4/Vn4p/JgpPxejmqaXOogCJF9uktW0byKwBak7dZurRjnAMMJccEzOxZ3ZIYGfJWdbd1mWWN2cHVRCstM4A=
    on:
      tags: true
      repo: PlanCZero/nodecli
    email:
      secure: zqPtLN3C3+g5eh2BUYDhn0OIG/FVpZ/YNp9QyJYn44xksA2GitqVBU6KQTapv16ohQoXpDtPOLPhwZGowEtiIeKKfGM7l3DO0kPcmX40lTOtkdmbSKPT2DaL/bHvttv/EkNysbVWAvp7wVitJBM3f8nTB63GziRTp8Y68nfyFd9v2M3DohOb3neCTRe+zDg6/NK3kacMGG1Mag+VPcDS/ZyvZ6WUy4aQgz7Z572hk2mOJMljBWNgWtvE7OdQU1nCkRfBACx+0FH19EdmpHiFMN4LjxjDfFch/AJCQj11wAE3iASS9+96t1DqT35wNzM4PGyZhU0mDl8jw0+IeLa+0L6Tvz/+RR82jC9W129NTZtxj8DYR9FOwwApUP6j/4u+PZCrisU2QBbvzDaOU2ReN3jv55xUn2zOKTx0FV6dSKVKbb2by79rglTeDvJ1sgLs05wEel3SK/aNeqrE7q/yTxqtF0I2oiogDeZDUe05aslIjVhVUb25nbL2CvHjXXyk/TBXpve78WBQxTMCN8pBrLJJZ/6PdjZU6OiyaT7HOyat5fIQUyB2oaiBUFqObHiRMwqWdX5MEo9gXahexQiWOvypqq+1X+vr5ZUwf44La5H+DS1aehbiV44tHRUAZd3WYiPoc0JPzsW7mX9fF+j5Gjj8qPeSz3zXKOMRo18cfXQ=
  - provider: script
    script: bash ./scripts/docker-deploy.sh
    skip_cleanup: true
    on:
      tags: true
      repo: PlanCZero/nodecli
env:
  global:
  - secure: A9HDyZU2fTtnbAZbFFP2T1x3DzTkM3HZJGVgmlh8MyvMp2sOiaL1r5e2T4Iv6+Pe2m7+G19OPW/q6vOPgqrSYVUbfpQRZJG8T+6CsKp0DiQeYyxd30EGFimD5+b6L9Okr06RCRKjLC1YbWVX7ef/KAZrIOfC3klXXqtox1K4vXcaI2PFOvnt/cUxfylPrnMA3haa/a4MmB0TYcPOzAMkgXlZev5xKJ97zU4hT5O2FxJ4LVohOB0i8yTEfAMx7ecWERQycTgLAez1K640xOA0IdhugukyzVhiE1o/J49agCCPtb2NtLmWlIUOTIdumPEQgc++nbv/AotV8EJN5/qX7huSgwp0QbBY5VoyqmifiROeINW1FClP4SH38RqshRbggHC6M+EHr5ZkbSD7zsKmT51IUy10iILuGopYBLOo19Q5W7EjZDb05shMbS2zf/2RSZEekzO36+I/7qbbhJ4NuTaxeurP2P0RqKu6jzwuu6LRTn9S3xRdUxS9tZnmTDh9QWU7rwBQKZhCffQ9j7ibHxPGnCj6rR+1P4EWLGrCbnpf5vM4AitwQNh3m/fyepv2mxCIGkIk30/bWkZxOI1iTeky6c+DRzSaVJoeQzKtBekXyRPemVz2G9GOqeCnvU7BvIXeP9WEOzdmeR4HDHfhVBzzoDJyuq1A4ixvPsbCxqI=
  - secure: trofmdHNQiIZPe7WhQbPHHFIglvewefoKfcjH2jM7RL691S4dwO+sbbdrw7m5MvWSuL/gI95+Mjfw6JWFy+o2t8VUPxeSi23Q5G/55wT6GHgnEV+7ngyVrI6hn6v31kguELsufZRDaBhLISkwEoErRaHIrJOcgxAUPY7e1Qy23ScwUdAC4vuUOe88IVuYcp5WoqfO2Z9tUENM1HBEdD0ER7l7uzn3b50nbgwm19RacM2lNI4BwHwZC3mK6p2z/EeFwrBKvf6EkX4nohQvkt7NEBVoixCka3ZKtUC+Qrsa+Hddt+xFWwMpjGLWDgdh8g50hvDGimBB7jgTK/Y+mBLdKun7cAkVxmA2XKmoaNlesrMcaJUfu/a6xsAgP0gM+SqyDHAN3+ZRqu3BLxJY5mFWzC+VqApaL2n1EIFKDCgcBf6BdVXWllnKYiaq0T2VggS1fVAsBxoulNE6ZeqEdqhUswH2xR/WsWOPfRBsFjW0YzhJc8zX6kYpnEm37VtEG5tmGbLsjznX5iuLh6SE3xui+F7lhX+gw6kozIIKtCGAE/UEMyPTzk6GY+ddXNrOsWBzVqT9MhC+ni22bukJquPSQKCCyQhuWZ91Gt34Adi/mSZKM90jbO9FxJHyvA4TzZ7SIE5fHtdjFT3fqdFcyBisuqjEpljVUIjxJr301dbmQs=
